name: iOS Unit Tests

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/ios-unit-tests.yml
      - ios/**
      - packages/**/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - tools/src/commands/IosNativeUnitTests.ts
      - tools/src/commands/NativeUnitTests.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
      - .ruby-version
      - '!packages/@expo/cli/**'
  push:
    branches: [main]
    paths:
      - .github/workflows/ios-unit-tests.yml
      - ios/**
      - packages/**/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - tools/src/commands/IosNativeUnitTests.ts
      - tools/src/commands/NativeUnitTests.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
      - .ruby-version
      - '!packages/@expo/cli/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    timeout-minutes: 60
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 🔨 Switch to Xcode 13.2.1
        run: sudo xcode-select --switch /Applications/Xcode_13.2.1.app
      - name: 🔓 Decrypt secrets if possible
        uses: ./.github/actions/expo-git-decrypt
        with:
          key: ${{ secrets.GIT_CRYPT_KEY_BASE64 }}
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 💎 Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: 'true'
          yarn-tools: 'true'
          ios-pods: 'true'
          bare-expo-pods: 'true'
      - name: 🧶 Yarn install
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: 🏭 Generating dynamic macros
        run: expotools ios-generate-dynamic-macros
      - name: 🥥 Install CocoaPods in `ios`
        if: steps.expo-caches.outputs.ios-pods-hit != 'true'
        run: pod install
        working-directory: ios
      - name: 🥥 Install CocoaPods in `apps/bare-expo/ios`
        if: steps.expo-caches.outputs.bare-expo-pods-hit != 'true'
        run: pod install
        working-directory: apps/bare-expo/ios
      - name: 🧪 Run native iOS unit tests
        timeout-minutes: 45
        run: expotools native-unit-tests --platform ios
